# Generated by Django 4.1.6 on 2023-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_book_pdf_book_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("csv", models.FileField(upload_to="books/csvs/")),
            ],
        ),
        migrations.CreateModel(
            name="TxtFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("txt", models.FileField(upload_to="books/txts/")),
            ],
        ),
        migrations.CreateModel(
            name="XlsxFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("xlsx", models.FileField(upload_to="books/xlsxs/")),
            ],
        ),
        migrations.DeleteModel(name="Book",),
    ]
